---
title: "R Programming Week 3, Debugging"
author: "Krista DeStasio"
date: "1/9/2017"
output: html_document
---
# Notes from R Programming, week 3
*Note: much of the following text is directly from the course slides, available here: [www.coursera.org/learn/r-programming](www.coursera.org/learn/r-programming)*
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Dropbox (PfeiBer Lab)/kdestasio/R_projects/coursera/r_programming/")
rm(list = ls())
list.of.packages <- c("datasets")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
library(datasets)
```
# DEBUGGING
Built into R. Can be useful for figuring out what's wrong after you've discovered there's a problem. 

## Something's Wrong!
Indications that something is not right:

- **message**: A generic notification/diagnostic message produced by the message function; execution of the function continues
- **warning**: An indication that something is wrong but not necessarily fatal; execution of the function continues; generated by the warning function
- **error**: An indication that a fatal problem has occurred; execution stops; produced by the stop function
- **condition**: A generic concept for indicating that something unexpected can occur; programmers can create their oen conditions
    + All 3 of the above are conditions
    + You can create custom conditions
